format_version: 3
pipelines:
  test-ios:
    group: Test
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/shakirshakiel/test-ios.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - test-ios:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - build
                command: make
                run_if: passed
